/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Mar 22 13:42:05 GMT 2026
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class CommandLine_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.CommandLine"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\alkhi\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "CA"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\alkhi\\Downloads\\commons-cli-master\\commons-cli-master"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\alkhi"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "alkhi"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CommandLine_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.cli.DeprecatedAttributes",
      "org.apache.commons.text.Builder",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderReader",
      "org.apache.commons.text.StringTokenizer",
      "org.apache.commons.text.TextStringBuilder",
      "org.apache.commons.cli.Option$Builder",
      "org.apache.commons.text.matcher.StringMatcher",
      "org.apache.commons.cli.TypeHandler",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderWriter",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderTokenizer",
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.CommandLine$Builder",
      "org.apache.commons.cli.Option$1",
      "org.apache.commons.cli.AlreadySelectedException",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.cli.OptionValidator",
      "org.apache.commons.cli.CommandLine$1",
      "org.apache.commons.cli.OptionGroup",
      "org.apache.commons.cli.CommandLine",
      "org.apache.commons.cli.Option",
      "org.apache.commons.cli.Util"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.function.Supplier", false, CommandLine_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CommandLine_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.CommandLine",
      "org.apache.commons.cli.CommandLine$Builder",
      "org.apache.commons.cli.Util",
      "org.apache.commons.cli.Option",
      "org.apache.commons.cli.OptionGroup",
      "org.apache.commons.cli.Option$Builder",
      "org.apache.commons.cli.OptionValidator",
      "org.apache.commons.text.TextStringBuilder",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.text.similarity.HammingDistance",
      "org.apache.commons.io.file.SimplePathVisitor",
      "org.apache.commons.io.file.NoopPathVisitor",
      "org.apache.commons.cli.DeprecatedAttributes",
      "org.apache.commons.io.file.CountingPathVisitor",
      "org.apache.commons.io.file.AccumulatorPathVisitor",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.CountingPathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.AccumulatorPathVisitor$Builder",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.io.file.Counters$LongPathCounters",
      "org.apache.commons.io.file.Counters$LongCounter",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.SymbolicLinkFileFilter",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.commons.io.file.Counters$BigIntegerPathCounters",
      "org.apache.commons.io.file.Counters$BigIntegerCounter",
      "org.apache.commons.io.file.StandardDeleteOption",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "org.apache.commons.io.filefilter.PathEqualsFileFilter",
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.TypeHandler",
      "org.apache.commons.cli.DeprecatedAttributes$Builder",
      "org.apache.commons.text.matcher.AbstractStringMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$NoneMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharSetMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$TrimMatcher",
      "org.apache.commons.text.matcher.StringMatcherFactory",
      "org.apache.commons.text.StringTokenizer",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderTokenizer",
      "org.apache.commons.lang3.ArrayUtils",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "org.apache.commons.io.file.PathUtils",
      "org.apache.commons.io.filefilter.MagicNumberFileFilter",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "org.apache.commons.io.filefilter.PathVisitorFileFilter",
      "org.hsqldb.jdbc.JDBCDriver",
      "org.apache.commons.text.similarity.LongestCommonSubsequenceDistance"
    );
  }
}
